
package com.fujfu.common.information.mongate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "wmgwSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmgwSoap {


    /**
     * 短信息发送接口
     * 
     * @param pszSubPort
     * @param pszMobis
     * @param userId
     * @param pszMsg
     * @param password
     * @param iMobiCount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MongateCsSpSendSmsNew", action = "http://tempuri.org/MongateCsSpSendSmsNew")
    @WebResult(name = "MongateCsSpSendSmsNewResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsSpSendSmsNew", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsSpSendSmsNew")
    @ResponseWrapper(localName = "MongateCsSpSendSmsNewResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsSpSendSmsNewResponse")
    public String mongateCsSpSendSmsNew(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pszMobis", targetNamespace = "http://tempuri.org/")
        String pszMobis,
        @WebParam(name = "pszMsg", targetNamespace = "http://tempuri.org/")
        String pszMsg,
        @WebParam(name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        int iMobiCount,
        @WebParam(name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        String pszSubPort);

    /**
     * 短信息发送接口
     * 
     * @param pszSubPort
     * @param pszMobis
     * @param userId
     * @param msgId
     * @param pszMsg
     * @param password
     * @param iMobiCount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MongateSendSubmit", action = "http://tempuri.org/MongateSendSubmit")
    @WebResult(name = "MongateSendSubmitResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateSendSubmit", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateSendSubmit")
    @ResponseWrapper(localName = "MongateSendSubmitResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateSendSubmitResponse")
    public String mongateSendSubmit(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "pszMobis", targetNamespace = "http://tempuri.org/")
        String pszMobis,
        @WebParam(name = "pszMsg", targetNamespace = "http://tempuri.org/")
        String pszMsg,
        @WebParam(name = "iMobiCount", targetNamespace = "http://tempuri.org/")
        int iMobiCount,
        @WebParam(name = "pszSubPort", targetNamespace = "http://tempuri.org/")
        String pszSubPort,
        @WebParam(name = "MsgId", targetNamespace = "http://tempuri.org/")
        String msgId);

    /**
     * 短信息发送接口
     * 
     * @param userId
     * @param multixmt
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "MongateMULTIXSend", action = "http://tempuri.org/MongateMULTIXSend")
    @WebResult(name = "MongateMULTIXSendResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateMULTIXSend", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateMULTIXSend")
    @ResponseWrapper(localName = "MongateMULTIXSendResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateMULTIXSendResponse")
    public String mongateMULTIXSend(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "multixmt", targetNamespace = "http://tempuri.org/")
        String multixmt);

    /**
     * 接收上行信息接口
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.fujfu.common.information.mongate.ArrayOfString
     */
    @WebMethod(operationName = "MongateCsGetSmsExEx", action = "http://tempuri.org/MongateCsGetSmsExEx")
    @WebResult(name = "MongateCsGetSmsExExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsGetSmsExEx", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsGetSmsExEx")
    @ResponseWrapper(localName = "MongateCsGetSmsExExResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsGetSmsExExResponse")
    public ArrayOfString mongateCsGetSmsExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 获取状态报告接口
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.fujfu.common.information.mongate.ArrayOfString
     */
    @WebMethod(operationName = "MongateCsGetStatusReportExEx", action = "http://tempuri.org/MongateCsGetStatusReportExEx")
    @WebResult(name = "MongateCsGetStatusReportExExResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateCsGetStatusReportExEx", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsGetStatusReportExEx")
    @ResponseWrapper(localName = "MongateCsGetStatusReportExExResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateCsGetStatusReportExExResponse")
    public ArrayOfString mongateCsGetStatusReportExEx(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 查询余额接口
     * 
     * @param userId
     * @param password
     * @return
     *     returns int
     */
    @WebMethod(operationName = "MongateQueryBalance", action = "http://tempuri.org/MongateQueryBalance")
    @WebResult(name = "MongateQueryBalanceResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateQueryBalance", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateQueryBalance")
    @ResponseWrapper(localName = "MongateQueryBalanceResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateQueryBalanceResponse")
    public int mongateQueryBalance(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 获取上行/状态报告接口
     * 
     * @param userId
     * @param iReqType
     * @param password
     * @return
     *     returns com.fujfu.common.information.mongate.ArrayOfString
     */
    @WebMethod(operationName = "MongateGetDeliver", action = "http://tempuri.org/MongateGetDeliver")
    @WebResult(name = "MongateGetDeliverResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MongateGetDeliver", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateGetDeliver")
    @ResponseWrapper(localName = "MongateGetDeliverResponse", targetNamespace = "http://tempuri.org/", className = "com.fujfu.common.information.mongate.MongateGetDeliverResponse")
    public ArrayOfString mongateGetDeliver(
        @WebParam(name = "userId", targetNamespace = "http://tempuri.org/")
        String userId,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "iReqType", targetNamespace = "http://tempuri.org/")
        int iReqType);

}
