
package com.fujfu.common.information.mongate;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "wmgw", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://ws.montnets.com:7791/MWGate/wmgw.asmx?wsdl")
public class Wmgw
    extends Service
{

    private final static URL WMGW_WSDL_LOCATION;
    private final static WebServiceException WMGW_EXCEPTION;
    private final static QName WMGW_QNAME = new QName("http://tempuri.org/", "wmgw");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.montnets.com:7791/MWGate/wmgw.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMGW_WSDL_LOCATION = url;
        WMGW_EXCEPTION = e;
    }

    public Wmgw() {
        super(__getWsdlLocation(), WMGW_QNAME);
    }

    public Wmgw(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMGW_QNAME, features);
    }

    public Wmgw(URL wsdlLocation) {
        super(wsdlLocation, WMGW_QNAME);
    }

    public Wmgw(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMGW_QNAME, features);
    }

    public Wmgw(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Wmgw(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap")
    public WmgwSoap getWmgwSoap() {
        return super.getPort(new QName("http://tempuri.org/", "wmgwSoap"), WmgwSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap")
    public WmgwSoap getWmgwSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wmgwSoap"), WmgwSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap12")
    public WmgwSoap getWmgwSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "wmgwSoap12"), WmgwSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmgwSoap
     */
    @WebEndpoint(name = "wmgwSoap12")
    public WmgwSoap getWmgwSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "wmgwSoap12"), WmgwSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMGW_EXCEPTION!= null) {
            throw WMGW_EXCEPTION;
        }
        return WMGW_WSDL_LOCATION;
    }

}
